language: c
os:
  - linux
dist:
  - bionic
cache:
  directories:
    - /home/travis/perl5
    - /home/travis/root
addons:
  apt:
    packages:
      - libtool-bin
      - libapr1-dev
      - libaprutil1-dev
      - perl-doc
      - lua5.3-dev
      - libbrotli-dev
      - libcurl4-openssl-dev
      - libsystemd-dev
      - libnghttp2-dev
      - libjansson-dev

matrix:
  include:
    - name: Linux Ubuntu, Default module set
    # -------------------------------------------------------------------------
    - name: Linux Ubuntu, Default, all-modules
      env: CONFIG="--enable-mods-shared=reallyall"
    # -------------------------------------------------------------------------
    - name: Linux Ubuntu, Prefork MPM, all-modules
      env: CONFIG="--enable-mods-shared=reallyall --with-mpm=prefork"
    # -------------------------------------------------------------------------
    - name: Linux Ubuntu, Worker MPM, all-modules
      env: CONFIG="--enable-mods-shared=reallyall --with-mpm=worker"
    # -------------------------------------------------------------------------
    - name: Linux Ubuntu, Shared MPMs, all-modules
      env: CONFIG="--enable-mods-shared=reallyall --enable-mpms-shared=all"
    # -------------------------------------------------------------------------
    - name: Linux Ubuntu, GCC 7 maintainer-mode w/-Werror
      os: linux
      env: CONFIG="--enable-mods-shared=reallyall --enable-maintainer-mode NOTEST_CFLAGS=-Werror CC=gcc-7"
           SKIP_TESTING=1
    # -------------------------------------------------------------------------
    - name: Linux Ubuntu, GCC 8 maintainer-mode w/-Werror
      env: CONFIG="--enable-mods-shared=reallyall --enable-maintainer-mode NOTEST_CFLAGS=-Werror CC=gcc-8"
           SKIP_TESTING=1
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - libtool-bin
            - libapr1-dev
            - libaprutil1-dev
            - perl-doc
            - lua5.3-dev
            - libbrotli-dev
            - libcurl4-openssl-dev
            - libsystemd-dev
            - libnghttp2-dev
            - libjansson-dev
    # -------------------------------------------------------------------------
    - if: branch != 2.4.x
      name: Linux Ubuntu, APR trunk
      env: APR_VERSION=trunk APR_CONFIG="--with-crypto"
           CONFIG="--enable-mods-shared=reallyall"
    # -------------------------------------------------------------------------
    - if: branch = 2.4.x
      name: Linux Ubuntu Xenial, all-modules
      os: linux
      dist: xenial
      env: CONFIG="--enable-mods-shared=reallyall"
    # -------------------------------------------------------------------------
    - name: Linux Ubuntu, APR 1.7.0, APR-util 1.6.1
      env: APR_VERSION=1.7.0 APU_VERSION=1.6.1
           CONFIG="--enable-mods-shared=reallyall"
           APU_CONFIG="--with-crypto"
    # -------------------------------------------------------------------------
    - name: Linux Ubuntu, APR 1.7.0 --enable-pool-debug, APR-util 1.6.1
      env: APR_VERSION=1.7.0 APR_CONFIG="--enable-pool-debug"
           APU_VERSION=1.6.1
           APU_CONFIG="--with-crypto"
           CONFIG="--enable-mods-shared=reallyall"
    # -------------------------------------------------------------------------
    - if: branch = 2.4.x
      name: Linux Ubuntu, APR 1.5.1, APR-util 1.5.4
      env: APR_VERSION=1.5.1 APU_VERSION=1.5.4
           CONFIG="--enable-mods-shared=reallyall"
    # -------------------------------------------------------------------------
    - if: branch = 2.4.x
      name: Linux Ubuntu, APR 1.4.8, APR-util 1.4.2
      env: APR_VERSION=1.4.8 APU_VERSION=1.4.2
           CONFIG="--enable-mods-shared=reallyall"
    # -------------------------------------------------------------------------

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib);
        cpanm --notest Net::SSL LWP::Protocol::https ExtUtils::Embed Test::More AnyEvent DateTime HTTP::DAV Protocol::HTTP2::Client FCGI;
    fi

before_script:
  - ./test/travis_before_${TRAVIS_OS_NAME}.sh

script:
  - ./test/travis_run_${TRAVIS_OS_NAME}.sh
